Repository green-code-initiative/creedengo-common, pull requests merged in 2023-12, with the labels that each got.

#24 implemented improvements for windows requirements tool
  tools/check_requirements/README.md
  tools/check_requirements/_config.sh
  tools/check_requirements/_core.sh
  tools/check_requirements/check_requirements.bat
  tools/check_requirements/config.txt
  tools/check_requirements/resources/check_require-capture-windows.png
Labels: enhancement, good first issue, 👀 👀 review done 👀 👀, 👀 👀 waiting commiter 👀 👀

#20 Adds documentation to publish new release of a plugin on SonarSource Marketplace
  doc/INSTALL.md
Labels: documentation, 👀 👀 review done 👀 👀, 👀 👀 waiting commiter 👀 👀

#25 Upgrade doc : process for rule deprecation
  doc/starter-pack.md
Labels: documentation
